language: python
env:
  - TOXENV=py27-django18-drf2
  - TOXENV=py33-django18-drf2
  - TOXENV=py27-django18-drf3
  - TOXENV=py33-django18-drf3
  - TOXENV=py27-django19-drf3
  - TOXENV=py34-django19-drf3
  - TOXENV=py27-django110-drf3
  - TOXENV=py34-django110-drf3

install:
  - pip install tox

script: tox -e $TOXENV
