language: python
env:
  - TOXENV=py27-django14
  - TOXENV=py32-django16
  - TOXENV=py32-django17
  - TOXENV=py33-django16
  - TOXENV=py33-django17

install:
  - pip install tox

script: tox -e $TOXENV
